### ISSUE TITLE
Can't figure out how to use repository - Send epub through email?

### ISSUE THREAD

**Issue by AtlanticMetal** [Patrick-Hogan/wandering_inn#5]
This is a gross misuse of the issue feature, but I was wondering if you could send an up to date epub to an attached email.

I fiddled with this for an hour, but I have no experience with git or python. I really just want to read the series... 

Email is softlaunchguy64@gmail.com if you are willing, if not delete. I'm not sure if you can attach files directly to an issue response, but that would also be great. Thanks for the help.

**Comment by Patrick-Hogan** [comment]
Apologies for the late response.

Since the material is copyrighted, I don't know that I can legally package and distribute it (packaging publicly-available material for personal use is, as I understand it, on pretty solid legal ground in the US at least; redistributing, not so much). 

I'm happy to help with troubleshooting, and I'm looking at packaging this with better email support into a docker image, which might make it easier for you to use.
